### PR TITLE
styling improvements

### PR DESCRIPTION
**Pull request by dksmith328**
Hi! 

I made a lot of changes to your styling on this application. I pretty much stripped the existing style and revamped it. I think it looks great. Let me know if you have any questions. I left some comments in the index.html document to explain what is going on. I hope you like the improvements. 

-Daniel

### CODE REVIEW

**Comment by bacloud14** [comment]
I pretty much like this new styling ! so thanks a lot David.
I have few preferences however:

- The landing page, where developer console is not yet open, should appear first. I liked that very much and it seems broken.
- `Loaded libraries:` section should be colorized as it is important to emphasize the current session.
- I always like a container background color, grey as it was or other light color. (the page seems a little empty without a background color now)
- I am having hard time testing locally again, because of CORD policy in modern browsers, did you test dynamic loading from CDN ?
- I like the new unified blue color so much. I adore the gloomy footer ! but would like the same color for header too :D 

It think that's it, let me know your preferences, 
Thank you for your valuable contribution

**Comment by dksmith328** [comment]
I will definitely make those changes. 

- I saw that you have the "error" div show until the console window was open, at which point the "options" div is opened. I was unable to get that to work on my browser, but I will try to get that functioning again. 
- I will colorize the Loaded Libraries section
- I will give the container backgrounds a color 
- Do you just want me to change the header font that says "Interactive Arrays" the same color as the footer? or do you want me to create a bar across the top similar to the footer? For now I will just change the font color.

**Comment by bacloud14** [comment]
great, thanks again for contribution, I appreciate this.
please work on the console open event, I can help you of you get stuck.
for the last point, yes, a background color as footer is nice I think.

thanks !

**Comment by dksmith328** [comment]
Hi! 

So I got the console open event to function properly.

-Added a background color to the containers
-Added a background color to the Loaded Libraries section

I didn't change the header much, but can if that's still an improvement you would like. 

Let me know :)

**Comment by bacloud14** [comment]
Just great ! thank you so much for contributing !

**Comment by dksmith328** [comment]
Hey! Not a problem. I am glad you liked the contributions. Let me know if you’d like any more styling help in the future.  Sent from Mail for Windows 10 From: AbenSent: Friday, January 15, 2021 12:47 PMTo: bacloud14/Interactive_ArraysCc: dksmith328; AuthorSubject: Re: [bacloud14/Interactive_Arrays] styling improvements (#8) Just great ! thank you so much for contributing !—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bacloud14** [comment]
Please, feel free, always welcome in my repos. let me know if you work on anything that matches my skills too.

Now focusing on https://github.com/bacloud14/SunnySunday and https://github.com/bacloud14/Secluded
(the later will go online in few hours 😃 It is cooking)

**Pull request merged**
